import pandas as pd
from dataclasses import dataclass, field
from pathlib import Path
import pandas as pd
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class ForcingData:
    """
    Time series boundary conditions (Rainfall, Evaporation)
    """
    data: pd.DataFrame = field(default_factory=pd.DataFrame)
    
    @classmethod
    def from_file(cls, filepath: str) -> 'ForcingData':
        path = Path(filepath)
        if not path.exists():
            raise FileNotFoundError("HERE ALSO")

            
        try:
            # Read file, skipping comment lines '#'
            df = pd.read_csv(path, sep=r'\s+', comment='#', header=None, engine='python')
            
            # Normalize columns: expect Time, Flag, Value
            if len(df.columns) >= 3:
                df = df.iloc[:, [0, 2]] # Keep Time and Value
                df.columns = ['time_s', 'value']
            elif len(df.columns) == 2:
                df.columns = ['time_s', 'value']
                
            return cls(data=df)
        except Exception:
            return cls()

    def to_file(self, filepath: str, time_unit: str = 's'):
        """Writes timeser.def"""
        path = Path(filepath)
        path.parent.mkdir(parents=True, exist_ok=True)
        
        factor = {'s': 1, 'min': 60, 'h': 3600, 'd': 86400}.get(time_unit, 1.0)
        
        with open(path, 'w') as f:
            f.write(f"# Rainfall time series generated by Python\n")
            f.write(f"# Time unit: {time_unit}\n")
            
            if not self.data.empty:
                for _, row in self.data.iterrows():
                    t = row['time_s'] / factor
                    v = row['value']
                    f.write(f"{t:15.6f}  1  {v:12.6e}\n")
